[package]
name = "log_example"
version.workspace = true
edition.workspace = true
license-file.workspace = true
authors.workspace = true

[dependencies]
mw_log.workspace = true
mw_log_fmt.workspace = true

[lints]
workspace = true
